<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kiwimpact.IntegrationTests" />
    <InternalsVisibleTo Include="Kiwimpact.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kiwimpact.Core\Kiwimpact.Core.csproj" />
    <ProjectReference Include="..\Kiwimpact.Infrastructure\Kiwimpact.Infrastructure.csproj" />
  </ItemGroup>

</Project>
