// <auto-generated />
using System;
using Kiwimpact.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiwimpact.Infrastructure.Migrations
{
    [DbContext(typeof(KiwimpactDbContext))]
    [Migration("20260807074101_AddCompletionCelebrationCopy")]
    partial class AddCompletionCelebrationCopy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiwimpact.Core.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Achievements_Code");

                    b.ToTable("Achievements", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.CommunityChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalAreaRegionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RewardAchievementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LocalAreaRegionId")
                        .IsUnique()
                        .HasDatabaseName("UX_CommunityChallenges_ActiveLocalArea")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("RewardAchievementId")
                        .HasDatabaseName("IX_CommunityChallenges_RewardAchievementId");

                    b.HasIndex("LocalAreaRegionId", "PeriodStart")
                        .HasDatabaseName("IX_CommunityChallenges_LocalArea_PeriodStart");

                    b.ToTable("CommunityChallenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommunityChallenges_Period", "\"PeriodEnd\" > \"PeriodStart\"");

                            t.HasCheckConstraint("CK_CommunityChallenges_TargetValue_Positive", "\"TargetValue\" > 0");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.CompletionCelebrationCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_CompletionCelebrationCopies_Kind_Order");

                    b.HasIndex("Kind", "Text")
                        .IsUnique()
                        .HasDatabaseName("UX_CompletionCelebrationCopies_Kind_Text");

                    b.ToTable("CompletionCelebrationCopies", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompletionCelebrationCopies_SortOrder_NonNegative", "\"SortOrder\" >= 0");

                            t.HasCheckConstraint("CK_CompletionCelebrationCopies_Text_NotBlank", "length(btrim(\"Text\")) > 0");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.CompletionCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QuestId")
                        .IsUnique()
                        .HasDatabaseName("UX_CompletionCodes_QuestId_Active")
                        .HasFilter("\"IsActive\" AND NOT \"IsRevoked\"");

                    b.HasIndex("QuestId", "IsActive", "IsRevoked")
                        .HasDatabaseName("IX_CompletionCodes_QuestId_IsActive_IsRevoked");

                    b.ToTable("CompletionCodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompletionCodes_ValidityWindow", "\"ValidTo\" IS NULL OR \"ValidTo\" > \"ValidFrom\"");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.EvidenceClaimDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("EvidencePurgeDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EvidencePurgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("QuestCompletionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UserDeclaration")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EvidencePurgeDueAt")
                        .HasDatabaseName("IX_EvidenceClaimDetails_PurgeDue")
                        .HasFilter("\"EvidencePurgedAt\" IS NULL");

                    b.HasIndex("QuestCompletionId")
                        .IsUnique()
                        .HasDatabaseName("UX_EvidenceClaimDetails_QuestCompletionId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("EvidenceClaimDetails", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.FeaturedPassportAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("IX_FeaturedPassportAchievements_AchievementId");

                    b.HasIndex("UserId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_FeaturedPassportAchievements_User_SortOrder");

                    b.ToTable("FeaturedPassportAchievements", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeaturedPassportAchievements_SortOrder", "\"SortOrder\" BETWEEN 0 AND 4");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.MemberRewardEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CelebrationMessage")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)");

                    b.Property<string>("CelebrationTitle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("CommunityChallengeId")
                        .HasColumnType("uuid");

                    b.Property<long?>("CommunityChallengePreviousProgress")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommunityChallengeProgress")
                        .HasColumnType("bigint");

                    b.Property<int?>("CommunityChallengeTarget")
                        .HasColumnType("integer");

                    b.Property<string>("CommunityName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasVerifiedImpactThisWeek")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("PreviousHasVerifiedImpactThisWeek")
                        .HasColumnType("boolean");

                    b.Property<int>("PreviousLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousRankTitle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("PreviousStreakWeeks")
                        .HasColumnType("integer");

                    b.Property<long>("PreviousTotalXp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("QuestCompletionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RankTitle")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("SeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StreakWeeks")
                        .HasColumnType("integer");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestCompletionId")
                        .IsUnique()
                        .HasDatabaseName("UX_MemberRewardEvents_QuestCompletionId");

                    b.HasIndex("UserId", "QuestId", "CreatedAt")
                        .HasDatabaseName("IX_MemberRewardEvents_User_Quest");

                    b.HasIndex("UserId", "SeenAtUtc", "CreatedAt")
                        .HasDatabaseName("IX_MemberRewardEvents_User_Inbox");

                    b.ToTable("MemberRewardEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberRewardEvents_CommunitySnapshot_Complete", "(\"CommunityChallengeId\" IS NULL AND \"CommunityName\" IS NULL AND \"CommunityChallengePreviousProgress\" IS NULL AND \"CommunityChallengeProgress\" IS NULL AND \"CommunityChallengeTarget\" IS NULL) OR (\"CommunityChallengeId\" IS NOT NULL AND \"CommunityName\" IS NOT NULL AND \"CommunityChallengePreviousProgress\" IS NOT NULL AND \"CommunityChallengeProgress\" IS NOT NULL AND \"CommunityChallengeTarget\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MemberRewardEvents_Level_Range", "\"Level\" BETWEEN 1 AND 99 AND \"PreviousLevel\" BETWEEN 1 AND 99");

                            t.HasCheckConstraint("CK_MemberRewardEvents_Streak_NonNegative", "\"StreakWeeks\" >= 0 AND \"PreviousStreakWeeks\" >= 0");

                            t.HasCheckConstraint("CK_MemberRewardEvents_TotalXp_Order", "\"TotalXp\" >= \"PreviousTotalXp\"");

                            t.HasCheckConstraint("CK_MemberRewardEvents_XpAwarded_Positive", "\"XpAwarded\" > 0");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.MemberRewardEventAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("RewardEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RewardEventId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("UX_MemberRewardEventAchievements_Event_Achievement");

                    b.HasIndex("RewardEventId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_MemberRewardEventAchievements_Event_Order");

                    b.ToTable("MemberRewardEventAchievements", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberRewardEventAchievements_SortOrder", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("EndAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalSourceStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExternalSourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("LocationRegionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset?>("NextCheckDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("SourceCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("StartAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("XpAward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Quests_CreatedByUserId");

                    b.HasIndex("LocationRegionId")
                        .HasDatabaseName("IX_Quests_LocationRegionId");

                    b.HasIndex("Status", "Category")
                        .HasDatabaseName("IX_Quests_Status_Category");

                    b.HasIndex("Status", "Difficulty")
                        .HasDatabaseName("IX_Quests_Status_Difficulty");

                    b.HasIndex("Status", "LocationRegionId")
                        .HasDatabaseName("IX_Quests_Status_LocationRegionId");

                    b.HasIndex("Status", "SourceType")
                        .HasDatabaseName("IX_Quests_Status_SourceType");

                    b.HasIndex("Status", "StartAtUtc")
                        .HasDatabaseName("IX_Quests_Status_StartAtUtc");

                    b.ToTable("Quests", null, t =>
                        {
                            t.HasCheckConstraint("CK_Quests_Capacity_NonNegative", "\"Capacity\" IS NULL OR \"Capacity\" >= 0");

                            t.HasCheckConstraint("CK_Quests_Coordinates_Paired", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Quests_Latitude_Range", "\"Latitude\" IS NULL OR \"Latitude\" BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Quests_Longitude_Range", "\"Longitude\" IS NULL OR \"Longitude\" BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_Quests_XpAward_NonNegative", "\"XpAward\" >= 0");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.QuestCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommunityRegionIdAtCompletion")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ParticipationId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestCategorySnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<string>("RewardDifficultySnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CommunityRegionIdAtCompletion");

                    b.HasIndex("ParticipationId")
                        .HasDatabaseName("IX_QuestCompletions_ParticipationId");

                    b.HasIndex("QuestId");

                    b.HasIndex("UserId", "QuestId")
                        .IsUnique()
                        .HasDatabaseName("UX_QuestCompletions_UserId_QuestId_Verified")
                        .HasFilter("\"Status\" = 'Verified'");

                    b.HasIndex("Method", "Status", "CreatedAt");

                    b.HasIndex("UserId", "QuestCategorySnapshot", "VerifiedAtUtc")
                        .HasDatabaseName("IX_QuestCompletions_UserId_CategorySnapshot_VerifiedAtUtc");

                    b.ToTable("QuestCompletions", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.QuestImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LicenceNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestId", "IsCover")
                        .HasDatabaseName("IX_QuestImages_QuestId_IsCover");

                    b.HasIndex("QuestId", "SortOrder")
                        .HasDatabaseName("IX_QuestImages_QuestId_SortOrder");

                    b.ToTable("QuestImages", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.QuestParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("IX_QuestParticipations_QuestId_Active")
                        .HasFilter("\"CancelledAt\" IS NULL");

                    b.HasIndex("UserId", "QuestId")
                        .IsUnique()
                        .HasDatabaseName("UX_QuestParticipations_UserId_QuestId_Active")
                        .HasFilter("\"CancelledAt\" IS NULL");

                    b.ToTable("QuestParticipations", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentRegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegionId")
                        .HasDatabaseName("IX_Regions_ParentRegionId");

                    b.HasIndex("Type", "IsActive")
                        .HasDatabaseName("IX_Regions_Type_IsActive");

                    b.HasIndex("Name", "Type", "ParentRegionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Regions_Name_Type_ParentRegionId");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Name", "Type", "ParentRegionId"), false);

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("IX_SocialComments_AuthorUserId");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("IX_SocialComments_ParentCommentId");

                    b.HasIndex("PostId", "ParentCommentId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_SocialComments_Post_Parent_CreatedAt_Id");

                    b.ToTable("SocialComments", null, t =>
                        {
                            t.HasCheckConstraint("CK_SocialComments_NotSelfParent", "\"ParentCommentId\" IS NULL OR \"ParentCommentId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageAltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceCompletionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("IX_SocialPosts_AuthorUserId");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("IX_SocialPosts_QuestId");

                    b.HasIndex("SourceCompletionId")
                        .IsUnique()
                        .HasDatabaseName("UX_SocialPosts_SourceCompletionId")
                        .HasFilter("\"SourceCompletionId\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("IX_SocialPosts_CreatedAt_Id");

                    b.ToTable("SocialPosts", null, t =>
                        {
                            t.HasCheckConstraint("CK_SocialPosts_ImageMetadata_Pair", "(\"ImageUrl\" IS NULL AND \"ImageAltText\" IS NULL) OR (\"ImageUrl\" IS NOT NULL AND \"ImageAltText\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPostImage", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("PostId", "SortOrder");

                    b.ToTable("SocialPostImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_SocialPostImages_SortOrder", "\"SortOrder\" >= 0 AND \"SortOrder\" < 9");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPostLike", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SocialPostLikes_UserId");

                    b.ToTable("SocialPostLikes", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("PostId", "NormalizedName");

                    b.ToTable("SocialPostTags", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceCommunityChallengeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("XpTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("IX_UserAchievements_AchievementId");

                    b.HasIndex("SourceCommunityChallengeId")
                        .HasDatabaseName("IX_UserAchievements_SourceCommunityChallengeId");

                    b.HasIndex("XpTransactionId")
                        .HasDatabaseName("IX_UserAchievements_XpTransactionId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAchievements_Milestone")
                        .HasFilter("\"SourceCommunityChallengeId\" IS NULL");

                    b.HasIndex("UserId", "AchievementId", "SourceCommunityChallengeId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserAchievements_CommunityChallenge")
                        .HasFilter("\"SourceCommunityChallengeId\" IS NOT NULL");

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AchievementEvaluationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("HomeCommunityRegionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublicPassportEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastCommunityChangeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("PublicPassportShareId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ShowCommunityOnPassport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AchievementEvaluationVersion");

                    b.HasIndex("HomeCommunityRegionId");

                    b.HasIndex("PublicPassportShareId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserProfiles_PublicPassportShareId")
                        .HasFilter("\"PublicPassportShareId\" IS NOT NULL");

                    b.ToTable("UserProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserProfiles_AchievementEvaluationVersion_NonNegative", "\"AchievementEvaluationVersion\" >= 0");

                            t.HasCheckConstraint("CK_UserProfiles_Level_Range", "\"Level\" BETWEEN 1 AND 99");

                            t.HasCheckConstraint("CK_UserProfiles_TotalXp_NonNegative", "\"TotalXp\" >= 0");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.XpTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommunityRegionIdAtAward")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceCompletionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceCompletionId")
                        .IsUnique()
                        .HasDatabaseName("UX_XpTransactions_SourceCompletionId");

                    b.HasIndex("CommunityRegionIdAtAward", "CreatedAt")
                        .HasDatabaseName("IX_XpTransactions_CommunityRegionIdAtAward_CreatedAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_XpTransactions_UserId_CreatedAt");

                    b.ToTable("XpTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_XpTransactions_XpAmount_Positive", "\"XpAmount\" > 0");
                        });
                });

            modelBuilder.Entity("Kiwimpact.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.CommunityChallenge", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Region", "LocalAreaRegion")
                        .WithMany()
                        .HasForeignKey("LocalAreaRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.Achievement", "RewardAchievement")
                        .WithMany()
                        .HasForeignKey("RewardAchievementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocalAreaRegion");

                    b.Navigation("RewardAchievement");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.CompletionCode", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.EvidenceClaimDetail", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.QuestCompletion", "QuestCompletion")
                        .WithOne("EvidenceClaimDetail")
                        .HasForeignKey("Kiwimpact.Core.Entities.EvidenceClaimDetail", "QuestCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("QuestCompletion");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.FeaturedPassportAchievement", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Achievement", null)
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.MemberRewardEvent", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.XpTransaction", "XpTransaction")
                        .WithOne()
                        .HasForeignKey("Kiwimpact.Core.Entities.MemberRewardEvent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.QuestCompletion", "QuestCompletion")
                        .WithOne()
                        .HasForeignKey("Kiwimpact.Core.Entities.MemberRewardEvent", "QuestCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("QuestCompletion");

                    b.Navigation("XpTransaction");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.MemberRewardEventAchievement", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.MemberRewardEvent", "RewardEvent")
                        .WithMany("UnlockedAchievements")
                        .HasForeignKey("RewardEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("RewardEvent");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.Quest", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.Region", "LocationRegion")
                        .WithMany("Quests")
                        .HasForeignKey("LocationRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocationRegion");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.QuestCompletion", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Region", "CommunityRegionAtCompletion")
                        .WithMany()
                        .HasForeignKey("CommunityRegionIdAtCompletion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kiwimpact.Core.Entities.QuestParticipation", "Participation")
                        .WithMany()
                        .HasForeignKey("ParticipationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kiwimpact.Core.Entities.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommunityRegionAtCompletion");

                    b.Navigation("Participation");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.QuestImage", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Quest", "Quest")
                        .WithMany("Images")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.QuestParticipation", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Quest", "Quest")
                        .WithMany("Participations")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.Region", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Region", "ParentRegion")
                        .WithMany("ChildRegions")
                        .HasForeignKey("ParentRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentRegion");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialComment", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.SocialComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kiwimpact.Core.Entities.SocialPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPost", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kiwimpact.Core.Entities.QuestCompletion", null)
                        .WithMany()
                        .HasForeignKey("SourceCompletionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPostImage", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.SocialPost", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPostLike", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.SocialPost", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPostTag", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.SocialPost", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.UserAchievement", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Achievement", null)
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.CommunityChallenge", null)
                        .WithMany()
                        .HasForeignKey("SourceCommunityChallengeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.XpTransaction", null)
                        .WithMany()
                        .HasForeignKey("XpTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.UserProfile", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Region", "HomeCommunityRegion")
                        .WithMany()
                        .HasForeignKey("HomeCommunityRegionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Kiwimpact.Core.Entities.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeCommunityRegion");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.XpTransaction", b =>
                {
                    b.HasOne("Kiwimpact.Core.Entities.Region", null)
                        .WithMany()
                        .HasForeignKey("CommunityRegionIdAtAward")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kiwimpact.Core.Entities.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Core.Entities.QuestCompletion", null)
                        .WithMany()
                        .HasForeignKey("SourceCompletionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Kiwimpact.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.MemberRewardEvent", b =>
                {
                    b.Navigation("UnlockedAchievements");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.Quest", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.QuestCompletion", b =>
                {
                    b.Navigation("EvidenceClaimDetail");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.Region", b =>
                {
                    b.Navigation("ChildRegions");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Kiwimpact.Core.Entities.SocialPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Likes");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
